
#ifndef SFXENUMS_HPP
#define SFXENUMS_HPP

#define MAX_NUM_SFXOBJS_PER_STATE 32

// TODO Location not confirmed
enum eMMTYPE {
    MMTYPE_MAIN = 0,
    MMTYPE_SECONDARY = 1,
    MMTYPE_DYNAMIC = 2,
    MMTYPE_SECONDARYDYNAMIC = 3,
};

// TODO location not confirmed (there are reflection typedefs to this)
enum eRACETYPE {
    eRACE_CIRCUIT = 0,
    eRACE_DRAG = 1,
    eRACE_TWOCIRC = 2,
    eRACE_TWODRG = 3,
};

enum eMAINMAPSTATES {
    eMM_MAIN = 0,
    eMM_MUSIC = 1,
    eMM_PLAYERCAR = 2,
    eMM_AIRACECAR = 3,
    eMM_COPCAR = 4,
    eMM_TRAFFIC = 5,
    eMM_ENVIRONMENT = 6,
    eMM_COLLISION = 7,
    eMM_DRIVEBY = 8,
    eMM_PLANE = 9,
    eMM_TRAIN = 10,
    eMM_HELICOPTER = 11,
    eMM_TRUCK = 12,
    eMM_MAX_MAIN_MIXSTATES = 13,
};

enum eCamStates {
    DMIX_DEFAULT_CAM = 0,
    DMIX_REAR_CAM = 0,
    DMIX_NFS_BUMPER_CAM = 1,
    DMIX_NFS_INCAR_CAM = 2,
    DMIX_NFS_JUMP_CAM = 3,
    DMIX_NFS_NIS_CAM = 4,
    DMIX_NFS_COLLISION_CAM = 5,
    MAX_DMIX_CAMS = 6,
};

enum eSFXOBJ_MAIN_TYPES {
    SFXOBJ_MUSIC = 0,
    SFXOBJ_SPEECH = 1,
    SFXOBJ_AMBIENCE = 2,
    SFXOBJ_MOVIES = 3,
    SFXOBJ_COMMON = 4,
    SFXOBJ_NISPROJ_STRMS = 5,
    SFXOBJ_MOMENT_STRMS = 6,
    SFXOBJ_FEHUD = 7,
};

typedef eSFXOBJ_MAIN_TYPES reflection_typedef_eSFXOBJ_MAIN_TYPES;

enum eVOL_WOOSH {
    eAZI_WOOSH_AZI = 0,
    eVOL_WOOSH_TREE = 1,
    eVOL_WOOSH_LAMPPOST = 2,
    eVOL_WOOSH_AICAR = 3,
    eVOL_WOOSH_TUNNEL_IN = 4,
    eVOL_WOOSH_TUNNEL_OUT = 5,
    eVOL_WOOSH_OVERPASS_IN = 6,
    eVOL_WOOSH_OVERPASS_OUT = 7,
    eVOL_WOOSH_SMOKABLE = 8,
    eVOL_WOOSH_BRIDGE = 9,
    eVOL_WOOSH_CAMERA_BY = 10,
    TRIG_WOOSH_EVENT = 11,
    TRIG_WOOSH_INTENSITY = 12,
    TRIG_WOOSH_CAMERA_BY = 13,
    ePCH_WOOSH_PITCH = 14,
    eVRB_WOOSH_VERB = 15,
};

typedef eVOL_WOOSH reflection_typedef_eVOL_WOOSH;

enum eSFX_NITROUS {
    SFX_NITROUS_NONE = 0,
    SFX_NITROUS_ON = 1,
};

typedef eSFX_NITROUS reflection_typedef_eSFX_NITROUS;

enum eVOL_ROADNOISE {
    eAZI_ROADNOISE_LEFT_AZ = 0,
    eAZI_ROADNOISE_RIGHT_AZ = 1,
    eVOL_ROADNOISE_TRANSITION = 2,
    eVOL_ROADNOISE_WET_ROAD = 3,
    eVOL_ROADNOISE_STITCH_TRANS = 4,
    eVOL_ROADNOISE_GRAVEL = 5,
    eVOL_ROADNOISE_SIDEWALK = 6,
    eVOL_ROADNOISE_COBBLESTONE = 7,
    eVOL_ROADNOISE_DEEPWATER = 8,
    eVOL_ROADNOISE_WETROAD = 9,
    eVOL_ROADNOISE_ASHPHALT = 10,
    eVOL_ROADNOISE_METAL = 11,
    eVOL_ROADNOISE_STITCH_LOOP = 12,
    eVOL_ROADNOISE_SPIKE = 13,
    eVOL_ROADNOISE_BLOWN = 14,
    eVRB_ROADNOISE_VERB = 15,
};

typedef eVOL_ROADNOISE reflection_typedef_eVOL_ROADNOISE;

enum eSFX_TURBO {
    SFXTURBO_NONE = 0,
    SFXTURBO_SPOOLING = 1,
    SFXTURBO_BLOWOFF = 2,
};

typedef eSFX_TURBO reflection_typedef_eSFX_TURBO;

enum eVOL_COLLISION {
    eAZI_COLLISION_COLLISION_AZI = 0,
    eAZI_COLLISION_SCRAPE_AZI = 1,
    eVOL_COLLISION_SMACKABLE_AZI = 2,
    eVOL_COLLISION_CAR_FRONT = 3,
    eVOL_COLLISION_CAR_SIDE = 4,
    eVOL_COLLISION_WORLD_ROLLOVER = 5,
    eVOL_COLLISION_WORLD_BOTTEMOUT = 6,
    eVOL_COLLISION_WORLD_WALL_FRONT = 7,
    eVOL_COLLISION_WORLD_WALL_SIDE = 8,
    eVOL_COLLISION_WORLD_CHAINFENCE = 9,
    eVOL_COLLISION_SMOKABLE_CAR = 10,
    eVOL_COLLISION_SMOKABLE_WORLD = 11,
    eVOL_COLLISION_SCRAPE = 12,
    eVRB_COLLISION_RVRB_COL = 13,
    eVRB_COLLISION_RVRB_SMAK = 14,
    eVRB_COLLISION_RVRB_SCRP = 15,
    ePCH_COLLISION_COL_PITCH = 16,
    ePCH_COLLISION_SMAK_PITCH = 17,
    ePCH_COLLISION_SCRAPE_PITCH = 18,
};

typedef eVOL_COLLISION reflection_typedef_eVOL_COLLISION;

enum eVOL_MOMENT {
    eAZI_MOMENT_3DPOS = 0,
    eVOL_MOMENT_JACKNIFE = 1,
    eVOL_MOMENT_COL_SWT = 2,
    eVOL_MOMENT_GASPUMP = 3,
    eVOL_MOMENT_BLOWNENGINE = 4,
    eVOL_MOMENT_PURSUIT_BREAKER = 5,
    eVOL_MOMENT_TOTALLED_ENGINE = 6,
    eVOL_MOMENT_JUMPCAM = 7,
    eVOL_MOMENT_THUNDER = 8,
    eVOL_MOMENT_GAMEPLAY = 9,
    eVOL_MOMENT_FLY_IN_CAM = 10,
    eVOL_MOMENT_SPOT_COP = 11,
    eVOL_MOMENT_PHOTOFINISH = 12,
};

typedef eVOL_MOMENT reflection_typedef_eVOL_MOMENT;

enum eREVERBFX {
    RVRB_CARSHOW_SML = 0,
    RVRB_CARSHOW_BASS = 1,
    RVRB_CARSHOW_BASS_2 = 2,
    RVRB_GARAGE = 3,
    RVRB_GARAGE_SML = 4,
    RVRB_SIMPLE_TUNNEL = 5,
    RVRB_SIMPLE_TUNNEL_SML = 6,
    RVRB_HILLS_CLOSE = 7,
    RVRB_HILLS = 8,
    RVRB_CITYOPEN = 9,
    RVRB_CITYDENSE = 10,
    RVRB_ALLEY = 11,
    RVRB_MAX_TYPES = 12,
};

#endif
