#ifndef AIBASICS_HPP
#define AIBASICS_HPP

#define NUM_AI_SKILL_LEVELS 10
#define NO_SKILL_LEVEL -1
#define PLAYER_SKILL_LEVEL -2

// Decl: 20
enum eTrafficDensity {
    eTRAFFICDENSITY_OFF = 0,
    eTRAFFICDENSITY_LOW = 1,
    eTRAFFICDENSITY_MEDIUM = 2,
    eTRAFFICDENSITY_HIGH = 3,
    NUM_TRAFFIC_DENSITIES = 4,
};

// Decl: 30
enum eOpponentStrength {
    eOPPONENTSTRENGTH_LOW = 0,
    eOPPONENTSTRENGTH_MEDIUM = 1,
    eOPPONENTSTRENGTH_HIGH = 2,
    NUM_OPPONENT_STRENGTHS = 3,
};

enum eAIDifficultyModifier {
    eAI_DIFFICULTY_MODIFIER_EASY = 0,
    eAI_DIFFICULTY_MODIFIER_SOMEWHAT_EASY = 1,
    eAI_DIFFICULTY_MODIFIER_NORMAL = 2,
    NUM_AI_DIFFICULTY_MODIFIERS = 3,
};

enum AIRacerNumbers {
    AI_RACER_1 = 100,
    AI_RACER_2 = 101,
    AI_RACER_3 = 102,
    AI_RACER_4 = 103,
    AI_RACER_5 = 104,
    AI_RACER_6 = 105,
    AI_RACER_7 = 106,
    AI_RACER_8 = 107,
};

#endif
