#ifndef FEREFLECTED_HPP
#define FEREFLECTED_HPP

// Decl: 14
enum eFEPartUpgradeLevels {
    PART_UPGRADE_LEVEL_UNSPECIFIED = -1,
    PART_UPGRADE_LEVEL_STOCK = 0,
    PART_UPGRADE_LEVEL_1 = 1,
    PART_UPGRADE_LEVEL_2 = 2,
    PART_UPGRADE_LEVEL_3 = 3,
    PART_UPGRADE_LEVEL_4 = 4,
    PART_UPGRADE_LEVEL_5 = 5,
    PART_UPGRADE_LEVEL_6 = 6,
    PART_UPGRADE_LEVEL_UNIQUE = 7,
    NUM_PART_UPGRADE_LEVELS = 8,
};

// Decl: 54
enum eUnlockableEntity {
    UNLOCKABLE_THING_UNKNOWN = 0,
    UNLOCKABLE_THING_CUSTOMIZE_PARTS = 1,
    UNLOCKABLE_THING_CUSTOMIZE_PERFORMANCE = 2,
    UNLOCKABLE_THING_CUSTOMIZE_VISUAL = 3,
    UNLOCKABLE_THING_PUT_TIRES = 4,
    UNLOCKABLE_THING_PUT_BRAKES = 5,
    UNLOCKABLE_THING_PUT_CHASSIS = 6,
    UNLOCKABLE_THING_PUT_TRANSMISSION = 7,
    UNLOCKABLE_THING_PUT_ENGINE = 8,
    UNLOCKABLE_THING_PUT_INDUCTION = 9,
    UNLOCKABLE_THING_PUT_NOS = 10,
    UNLOCKABLE_THING_BODY_KIT = 11,
    UNLOCKABLE_THING_SPOILERS = 12,
    UNLOCKABLE_THING_RIM_BRANDS = 13,
    UNLOCKABLE_THING_HOODS = 14,
    UNLOCKABLE_THING_ROOF_SCOOPS = 15,
    UNLOCKABLE_THING_LICENSE_PLATE = 16,
    UNLOCKABLE_THING_CUSTOM_HUD = 17,
    UNLOCKABLE_THING_WINDOW_TINT = 18,
    UNLOCKABLE_THING_PAINT_METALLIC = 19,
    UNLOCKABLE_THING_PAINT_PEARL = 20,
    UNLOCKABLE_THING_PAINT_GLOSS = 21,
    UNLOCKABLE_THING_PAINT_STOCK = 22,
    UNLOCKABLE_THING_PAINTABLE_BODY = 23,
    UNLOCKABLE_THING_PAINTABLE_RIMS = 24,
    UNLOCKABLE_THING_RIM_BRAND_5_ZIGEN = 25,
    UNLOCKABLE_THING_RIM_BRAND_ADR = 26,
    UNLOCKABLE_THING_RIM_BRAND_BBS = 27,
    UNLOCKABLE_THING_RIM_BRAND_ENKEI = 28,
    UNLOCKABLE_THING_RIM_BRAND_KONIG = 29,
    UNLOCKABLE_THING_RIM_BRAND_LOWENHART = 30,
    UNLOCKABLE_THING_RIM_BRAND_RACING_HART = 31,
    UNLOCKABLE_THING_RIM_BRAND_OZ = 32,
    UNLOCKABLE_THING_RIM_BRAND_VOLK = 33,
    UNLOCKABLE_THING_RIM_BRAND_ROJA = 34,
    UNLOCKABLE_VINYLS_GROUP_FLAME = 35,
    UNLOCKABLE_VINYLS_GROUP_TRIBAL = 36,
    UNLOCKABLE_VINYLS_GROUP_STRIPE = 37,
    UNLOCKABLE_VINYLS_GROUP_RACING_FLAG = 38,
    UNLOCKABLE_VINYLS_GROUP_NATIONAL_FLAG = 39,
    UNLOCKABLE_VINYLS_GROUP_BODY = 40,
    UNLOCKABLE_VINYLS_GROUP_UNIQUE = 41,
    UNLOCKABLE_VINYLS_GROUP_CONTEST = 42,
    UNLOCKABLE_DECAL_NUMBERS = 43,
    UNLOCKABLE_DECAL_WINDSHIELD = 44,
    UNLOCKABLE_DECAL_REAR_WINDOW = 45,
    UNLOCKABLE_DECAL_LEFT_DOOR = 46,
    UNLOCKABLE_DECAL_RIGHT_DOOR = 47,
    UNLOCKABLE_DECAL_LEFT_QP = 48,
    UNLOCKABLE_DECAL_RIGHT_QP = 49,
    UNLOCKABLE_DECAL_HOOD = 50,
    UNLOCKABLE_DECAL_SLOT_1 = 51,
    UNLOCKABLE_DECAL_SLOT_2 = 52,
    UNLOCKABLE_DECAL_SLOT_3 = 53,
    UNLOCKABLE_DECAL_SLOT_4 = 54,
    UNLOCKABLE_DECAL_SLOT_5 = 55,
    UNLOCKABLE_DECAL_SLOT_6 = 56,
    NUM_UNLOCKABLES = 57,
};

// total size: 0xC
// Decl: 295
struct FECarPartInfo {
    eFEPartUpgradeLevels Level; // offset 0x0, size 0x4, Decl: 296
    float Rep;                  // offset 0x4, size 0x4
    float Cost;                 // offset 0x8, size 0x4, Decl: 299
};

struct type_bStringHash {
    unsigned int hash; // offset 0x0, size 0x4, Decl: 308
};

#endif
