#ifndef __FEPACKAGEFILE_H__
#define __FEPACKAGEFILE_H__

#include "types.h"

static const u32 FENG_PACKAGE_VERSION = 0x10002; // size: 0x4, Decl: 26
static const u32 FENG_ALIGNMENT_SIZE = 16;       // size: 0x4, Decl: 27

#define GET_ID(id) (*(i32 *)(&(id)))                                        // :38
#define BCHUNK_FENG_NULL DATA_FECHUNK                                       // :48
#define BCHUNK_FENG_FILE GET_ID("FENG") | NESTED_FECHUNK                    // :50
#define BCHUNK_FENG_OBJECTLIST GET_ID("OLST") | NESTED_FECHUNK              // :62
#define BCHUNK_FENG_GROUPLIST GET_ID("GLST") | NESTED_FECHUNK               // :70
#define BCHUNK_FENG_TYPELIST GET_ID("TYPL") | NESTED_FECHUNK                // :78
#define BCHUNK_FENG_TYPENODE GET_ID("TNOD") | NESTED_FECHUNK                // :86
#define BCHUNK_FENG_TYPEFIELD GET_ID("TFIE") | DATA_FECHUNK                 // :95
#define BCHUNK_FENG_WSTRING GET_ID("WSTR") | DATA_FECHUNK                   // :110
#define BCHUNK_FENG_WSTRING_JUSTIFICATION GET_ID("JUST") | DATA_FECHUNK     // :122
#define BCHUNK_FENG_WSTRING_LEADING GET_ID("LEAD") | DATA_FECHUNK           // :134
#define BCHUNK_FENG_PACKAGEHEADER GET_ID("PKHD") | DATA_FECHUNK             // :144
#define BCHUNK_FENG_REQUEST GET_ID("RQST") | DATA_FECHUNK                   // :161
#define BCHUNK_FENG_RESOURCEREQUESTARRAY GET_ID("RQAR") | DATA_FECHUNK      // :185
#define BCHUNK_FENG_RESOURCELIST GET_ID("RLST") | NESTED_FECHUNK            // :196
#define BCHUNK_FENG_OBJECTYPEINFO GET_ID("OTPI") | DATA_FECHUNK             // :207
#define BCHUNK_FENG_OBJECTDATA GET_ID("ODAT") | NESTED_FECHUNK              // :219
#define BCHUNK_FENG_OBJECTTYPE GET_ID("OTYP") | DATA_FECHUNK                // :230
#define BCHUNK_FENG_OBJECTNAME GET_ID("ONAM") | DATA_FECHUNK                // :241
#define BCHUNK_FENG_GUID GET_ID("GUID") | DATA_FECHUNK                      // :252
#define BCHUNK_FENG_NUMBER GET_ID("NUMB") | DATA_FECHUNK                    // :253
#define BCHUNK_FENG_FLOAT GET_ID("FLOT") | DATA_FECHUNK                     // :263
#define BCHUNK_FENG_RECT GET_ID("RECT") | DATA_FECHUNK                      // :273
#define BCHUNK_FENG_POINT GET_ID("PONT") | DATA_FECHUNK                     // :286
#define BCHUNK_FENG_MESSAGERESPONSENAMES GET_ID("RSPN") | DATA_FECHUNK      // :297
#define BCHUNK_FENG_MESSAGERESPONSE GET_ID("MSGR") | DATA_FECHUNK           // :313
#define BCHUNK_FENG_RESPONSELIST GET_ID("RSPL") | NESTED_FECHUNK            // :324
#define BCHUNK_FENG_NAMEDMESSAGERESPONSE GET_ID("NRSP") | DATA_FECHUNK      // :342
#define BCHUNK_FENG_NAMEDRESPONSELIST GET_ID("NRSL") | NESTED_FECHUNK       // :353
#define BCHUNK_FENG_COMPLETERESPONSE GET_ID("CMRS") | NESTED_FECHUNK        // :363
#define BCHUNK_FENG_COMPLETEMESSAGERESPONSE GET_ID("CRSP") | NESTED_FECHUNK // :377
#define BCHUNK_FENG_COMPLETERESPONSELIST GET_ID("CRSL") | NESTED_FECHUNK    // :389
#define BCHUNK_FENG_SCRIPTDATA GET_ID("SCRD") | DATA_FECHUNK                // :399
#define BCHUNK_FENG_SCRIPTKEYTRACK GET_ID("STRK") | DATA_FECHUNK            // :419
#define BCHUNK_FENG_SCRIPTEVENTLIST GET_ID("EVTL") | DATA_FECHUNK           // :443
#define BCHUNK_FENG_SCRIPT GET_ID("SCRT") | NESTED_FECHUNK                  // :454
#define BCHUNK_FENG_SCRIPTLIST GET_ID("SCRL") | NESTED_FECHUNK              // :467
#define BCHUNK_FENG_STATE GET_ID("STTE") | DATA_FECHUNK                     // :478
#define BCHUNK_FENG_LISTBOXCELL GET_ID("LSCD") | NESTED_FECHUNK             // :489
#define BCHUNK_FENG_LISTBOXCELLARRAY GET_ID("LSCA") | NESTED_FECHUNK        // :505
#define BCHUNK_FENG_LISTBOXENTRYDATA GET_ID("LSED") | NESTED_FECHUNK        // :515
#define BCHUNK_FENG_LISTBOXENTRYARRAY GET_ID("LSEA") | NESTED_FECHUNK       // :526
#define BCHUNK_FENG_LISTBOX GET_ID("LIST") | NESTED_FECHUNK                 // :536
#define BCHUNK_FENG_CODELISTBOXCELL GET_ID("CLCD") | NESTED_FECHUNK         // :559
#define BCHUNK_FENG_CODELISTBOXCELLARRAY GET_ID("CLCA") | NESTED_FECHUNK    // :570
#define BCHUNK_FENG_CODELISTBOX GET_ID("CLST") | NESTED_FECHUNK             // :580
#define BCHUNK_FENG_BASEOBJECT GET_ID("BOBJ") | NESTED_FECHUNK              // :606
#define BCHUNK_FENG_MSGTARGETLISTARRAY GET_ID("MTLA") | NESTED_FECHUNK      // :632
#define BCHUNK_FENG_MSGTARGETLIST GET_ID("MTAR") | NESTED_FECHUNK           // :643
#define BCHUNK_FENG_BUTTONMAP GET_ID("BUTM") | NESTED_FECHUNK               // :656

#endif
