#!/usr/bin/env python3

###
# Splits the ELF according to the config.yml and generates a config.json based on it
#
# Usage:
#   python3 tools/delink_to_config_json.py config/VERSION/config.yml build/VERSION
###

import argparse
from pathlib import Path
import subprocess
import json
import yaml


def generate_config_json(delink_path: Path, config_yml: Path, build_folder: Path) -> str:
    with config_yml.open("r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    target_path = config["target_path"]
    splits_path = config["splits_path"]
    symbols_path = config["symbols_path"]
    splits = config["splits"]
    
    delink_args = [
        delink_path.as_posix(),
        "ida-split",
        symbols_path,
        target_path,
        "--idapro",
        splits_path,
        "-o",
        (build_folder / "obj").as_posix(),
    ]

    subprocess.run(delink_args, check=True)


    config_json = {
        "version": "1.7.0",
        "name": "main",
        "module_id": 0,  # TODO for rels
        "ldscript": (build_folder / "ldscript.ld").as_posix(),
        "entry": "__start",  # TODO
        "units": [],
        "extract": [],
        "modules": [],
        "links": [],
    }

    split: str
    for split in splits:
        src_path = split
        print((build_folder / "obj" / src_path))
        obj_path = (build_folder / "obj" / src_path).as_posix().removesuffix(
            ".s"
        ).removesuffix(".cpp").removesuffix(".c") + ".obj"

        config_json["units"].append(
            {
                "object": obj_path,
                "name": src_path,
                "autogenerated": False,  # TODO
                "code_size": 0,  # these are not needed
                "data_size": 0,
            }
        )

    return json.dumps(config_json)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="""Splits the configured binary and generates a config.json"""
    )
    parser.add_argument(
        "delink_path",
        help="""Path to the delink executable""",
    )
    parser.add_argument(
        "yml_file",
        help="""Config yml in""",
    )
    parser.add_argument(
        "build_folder",
        help="""Build folder out""",
    )
    args = parser.parse_args()

    output = generate_config_json(Path(args.delink_path), Path(args.yml_file), Path(args.build_folder))

    with open(Path(args.build_folder) / "config.json", "w", encoding="UTF-8") as f:
        f.write(output)


if __name__ == "__main__":
    main()
